# Vectors, Matrices, and Arrays

## 1.Creating a Vector

In [1]:
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
 [2],
[3]])

## 2.Creating a Matrix

In [ ]:
# Load library
import numpy as np
# Create a matrix
matrix = np.array([[1, 2],
 [1, 2],
 [1, 2]])

NumPy actually has a dedicated matrix data structure:

In [ ]:
matrix_object = np.mat([[1, 2],
 [1, 2],
 [1, 2]])
matrix([[1, 2],
 [1, 2],
 [1, 2]])

However, the matrix data structure is not recommended for two reasons. First, arrays
are the de facto standard data structure of NumPy. Second, the vast majority of
NumPy operations return arrays, not matrix objects.

## 3.Creating a Sparse Matrix

In [2]:
# Load libraries
import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
 [0, 1],
 [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


 there are many different types of sparse matrices, such as compressed
sparse column, list of lists, and dictionary of keys.

## 4. Selecting Elements

In [6]:
# Load library
import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [7]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [8]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [9]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [10]:
# Select the last element
vector[-1]

6

In [11]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

## 5.Describing a Matrix